export const patients = [
  {
    id: '1',
    namePatient: 'Ana Beatriz Lima',
    entryDate: '01/06/25',
    contact: '(11) 91234-5678',
    email: 'ana.lima@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '2',
    namePatient: 'Carlos Henrique Silva',
    entryDate: '28/05/25',
    contact: '(21) 99876-5432',
    email: 'carlos.silva@example.com',
    status: 'Inativo',
    actions: '⋮',
  },
  {
    id: '3',
    namePatient: 'Fernanda Costa',
    entryDate: '03/06/25',
    contact: '(31) 98765-4321',
    email: 'fernanda.costa@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '4',
    namePatient: 'João Pedro Oliveira',
    entryDate: '30/05/25',
    contact: '(41) 91234-1234',
    email: 'joao.oliveira@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '5',
    namePatient: 'Mariana Rocha',
    entryDate: '05/06/25',
    contact: '(51) 98765-6789',
    email: 'mariana.rocha@example.com',
    status: 'Inativo',
    actions: '⋮',
  },
  {
    id: '6',
    namePatient: 'Ricardo Martins',
    entryDate: '25/05/25',
    contact: '(61) 99999-0000',
    email: 'ricardo.martins@example.com',
    status: 'Inativo',
    actions: '⋮',
  },
  {
    id: '7',
    namePatient: 'Tatiane Souza',
    entryDate: '02/06/25',
    contact: '(71) 91234-5678',
    email: 'tatiane.souza@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '8',
    namePatient: 'Gabriel Nunes',
    entryDate: '29/05/25',
    contact: '(81) 99876-1234',
    email: 'gabriel.nunes@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '9',
    namePatient: 'Juliana Mendes',
    entryDate: '04/06/25',
    contact: '(91) 98765-9876',
    email: 'juliana.mendes@example.com',
    status: 'Inativo',
    actions: '⋮',
  },
  {
    id: '10',
    namePatient: 'Lucas Ferreira',
    entryDate: '01/06/25',
    contact: '(85) 99988-7766',
    email: 'lucas.ferreira@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '11',
    namePatient: 'Mariana Rocha',
    entryDate: '02/06/25',
    contact: '(11) 98877-6655',
    email: 'mariana.rocha@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '12',
    namePatient: 'Carlos Eduardo',
    entryDate: '03/06/25',
    contact: '(21) 99777-1122',
    email: 'carlos.edu@example.com',
    status: 'Inativo',
    actions: '⋮',
  },
  {
    id: '13',
    namePatient: 'Ana Clara Silva',
    entryDate: '04/06/25',
    contact: '(31) 98765-4321',
    email: 'ana.clara@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '14',
    namePatient: 'Felipe Andrade',
    entryDate: '05/06/25',
    contact: '(41) 99911-2233',
    email: 'felipe.andrade@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '15',
    namePatient: 'Beatriz Souza',
    entryDate: '06/06/25',
    contact: '(51) 99822-3344',
    email: 'beatriz.souza@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '16',
    namePatient: 'Rafael Lima',
    entryDate: '07/06/25',
    contact: '(61) 99733-4455',
    email: 'rafael.lima@example.com',
    status: 'Inativo',
    actions: '⋮',
  },
  {
    id: '17',
    namePatient: 'Lívia Martins',
    entryDate: '08/06/25',
    contact: '(71) 99644-5566',
    email: 'livia.martins@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '18',
    namePatient: 'Pedro Henrique',
    entryDate: '09/06/25',
    contact: '(91) 99555-6677',
    email: 'pedro.henrique@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
  {
    id: '19',
    namePatient: 'Camila Torres',
    entryDate: '10/06/25',
    contact: '(81) 99466-7788',
    email: 'camila.torres@example.com',
    status: 'Inativo',
    actions: '⋮',
  },
  {
    id: '20',
    namePatient: 'Gustavo Nunes',
    entryDate: '11/06/25',
    contact: '(13) 99377-8899',
    email: 'gustavo.nunes@example.com',
    status: 'Ativo',
    actions: '⋮',
  },
]
